export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOGGED_IN = "SET_LOGGED_IN";

// session types
export const GET_SESSION = "GET_SESSION";
export const SESSION_LOADING = "SESSION_LOADING";
export const SESSION_NOT_FOUND = "SESSION_NOT_FOUND";
export const CLEAR_CURRENT_SESSION = "CLEAR_CURRENT_SESSION";
export const GET_SESSIONS = "GET_SESSIONS";
export const SET_CURRENT_SESSION = "SET_CURRENT_SESSION";
export const STORY_SELECT = "STORY_SELECT";
export const SET_NEWLY_CREATED_SESSION = "SET_NEWLY_CREATED_SESSION";
export const GET_SESSION_STORIES = "GET_SESSION_STORIES";
export const SHOW_POKER_TOGGLE = "SHOW_POKER_TOGGLE";
